language: java

# explicit distribution specification
# to use xvfb as a service
dist: xenial

jdk: openjdk8

services:
   - docker
   - xvfb

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f com.examples.school/pom.xml clean verify
